### ISSUE TITLE
"Cannot navigate to invalid URL" when having special characters in the URL

### ISSUE THREAD

**Issue by jlnostr** [JakePartusch/lumberjack#6]
When having umlauts or other special characters, `lumberjack` fails with the message:

>   Protocol error (Page.navigate): Cannot navigate to invalid URL

Steps to reproduce:
- Invoke `lumberjack --url https://velo.rent`

**Comment by jlnostr** [comment]
I actually don't know either, but the sitemap was generated by the default Hugo template, so I assume they are valid. :D

**Comment by JakePartusch** [comment]
Ok cool. @jlnostr, If you want to take a stab at a fix, that would be awesome! 🎉 

Otherwise, I'll get around to it soon-ish
